<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-A3CNVOI4" failures="2" tests="3" name="Test" time="27.614" errors="0" timestamp="2023-02-17T08:52:18 IST">
  <testcase classname="TestCases.verifyLogin" name="login" time="0.051">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	url message is not matching expected [https://www.salesforce.com/] but found [https://login.salesforce.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
url message is not matching expected [https://www.salesforce.com/] but found [https://login.salesforce.com/]
at Resources.commonMethods.handleAssertions(commonMethods.java:26)
at TestCases.verifyLogin.login(verifyLogin.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="TestCases.verifyLogin" name="login" time="0.011">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	url message is not matching expected [https://www.salesforce.com/] but found [https://login.salesforce.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
url message is not matching expected [https://www.salesforce.com/] but found [https://login.salesforce.com/]
at Resources.commonMethods.handleAssertions(commonMethods.java:26)
at TestCases.verifyLogin.login(verifyLogin.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="TestCases.verifySignup" name="signup" time="7.156"/>
</testsuite> <!-- Test -->
